name: Documentation Website Deployment

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install library dependencies
        run: npm install
      - name: Build library
        run: npm run build:prod
      - name: Install website dependencies
        working-directory: ./website
        run: npm install
      - name: Build documentation website
        working-directory: ./website
        run: npm run build
      - name: Install plugin example dependencies
        working-directory: ./plugin-examples
        run: npm install
      - name: Build plugin examples website
        working-directory: ./plugin-examples
        run: npm run build:examples:site
      - name: Build plugin examples website
        working-directory: ./plugin-examples
        run: npm run build:examples:site


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/axadiw/lightweight-charts:${{  github.ref_name }}
